export const types = Object.freeze({
    // Sync
    PEOPLE_START_FETCHING:     'PEOPLE_START_FETCHING',
    PEOPLE_STOP_FETCHING:      'PEOPLE_STOP_FETCHING',
    PEOPLE_FILL:               'PEOPLE_FILL',
    PEOPLE_SET_FETCHING_ERROR: 'PEOPLE_SET_FETCHING_ERROR',
    PEOPLE_SET_CURRENT_PERSON: 'PEOPLE_SET_CURRENT_PERSON',

    // Async
    PEOPLE_FETCH_ASYNC: 'PEOPLE_FETCH_ASYNC',
});
